title: Linked Data Pipeline
description: Linked Data Pipeline
remote_theme: just-the-docs/just-the-docs@v0.5.3

favicon_ico: "/assets/images/favicon.ico"

callouts:
  note:
    title: Note
    color: yellow

aux_links:
  LDI Repository: https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-9F4LJXRX6T
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Define Jekyll collections
collections:
  core:
    permalink: "/:collection/:path"
    output: true
  ldio:
    permalink: "/:collection/:path"
    output: true
  ldi-nifi:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  collections:
    ldio:
      name: Linked Data Pipeline
    ldi-nifi:
      name: LD Pipeline in Apache NiFi
    core:
      name: LD Pipeline Core Building Blocks

enable_copy_code_button: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Contribute on GitHub"
gh_edit_repository: "https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"